import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from '@/api/QueryProvider';
import { AuthProvider } from '@/api/AuthContext';
import { PropsWithChildren } from 'react';
import { Sidebar } from '@/app/Sidebar';
import { Header } from '@/app/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex justify-between`}
      >
        <AuthProvider>
          <QueryProvider>
            <Sidebar />
            <div className="flex-1">
              <Header/>
              <main className="max-w-7xl mx-auto py-4">
                {children}
              </main>
            </div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
